#!/bin/bash

# check commands: slopBed, bedGraphToBigWig and bedClip

#which bedtools &>/dev/null || { echo "bedtools not found! Download bedTools: <http://code.google.com/p/bedtools/>"; exit 1; }
#which bedGraphToBigWig &>/dev/null || { echo "bedGraphToBigWig not found! Download: <http://hgdownload.cse.ucsc.edu/admin/exe/>"; exit 1; }
#which bedClip &>/dev/null || { echo "bedClip not found! Download: <http://hgdownload.cse.ucsc.edu/admin/exe/>"; exit 1; }

BGTBW=$mltool/scripts/bedGraphToBigWig
BC=$mltool/scripts/bedClip
BT=$BIOCODERS/Applications/bedtools

# end of checking
echoerr() { printf "%s\n" "$*" >&2; }

echoerr Checking arguments
if [ $# -lt 2 ];then
    echo "Need 2 parameters! <bedgraph> <chrom info>"
    exit
fi

F=$1
G=$2

echoerr Starting bed tools
$BT slop -i ${F} -g ${G} -b 0 | $BC stdin ${G} ${F}.clip

echoerr LC Collate
LC_COLLATE=C sort -k1,1 -k2,2n ${F}.clip > ${F}.sort.clip

echoerr Starting bedGraphToBigWig
### Added '.' before 'bdg' and 'bw' because was changing directory name 55_st_bdgcmp to 55_st_bwcmp
$BGTBW ${F}.sort.clip ${G} ${F/.bdg/.bw}

echoerr Final removal
rm -f ${F}.clip ${F}.sort.clip
